### ISSUE TITLE
 use middlewares Error

### ISSUE THREAD

**Issue by aizxin** [nanoexpress/pro-slim#30]
use middlewares 
```
import nanoexpress from '@nanoexpress/pro-slim';

function two(req, res, next) {
    req.two = true;
    next();
}
  
const app = nanoexpress();
app.use(two)  

app.get('/', async () => {
    return ({ status: 'ok' });
});

app.listen(3000);
```

Error:Only Async Functions are allowed to expose route

**Comment by dalisoft** [comment]
**pro-slim** allows only async route and middlewares!

It's mentioned in: https://nanoexpress.js.org -> Installation section -> pro-slim tab

**Comment by dalisoft** [comment]
If you need sync variant, try pro and simple versions. They both are supports sync variant
